# cfg-exporter 配置模板

# 配置文件路径
source = "./samples/configs"
# 配置文件支持的格式
import_extension = ["csv", "xlsx"]
# 字段描述行号
field_comment_row = 1
# 字段类型行号
field_type_row = 2
# 字段约束行号
field_constraint_row = 3
# 主体数据起始行号
body_start_row = 6

# typescript导出配置
[schema.typescript]
# 字段名行号
field_name_row = 4
# 导出目标路径
destination = "./samples/ts/"

# Erlang导出配置
[schema.erlang]
# 字段名行号
field_name_row = 5
# 导出目标路径
destination = "./samples/erlang/"
# 文件前缀
file_prefix = "cfg"
# record前缀
record_prefix = "cfg"
