# cfg-exporter 配置模板

# 配置文件路径
source = "./samples/configs"
# 字段描述行号
field_comment_row = 1
# 字段类型行号
field_type_row = 2
# 字段装饰器行号
field_decorator_row = 3
# 主体数据起始行号
body_start_row = 6

[schema.json]
# 字段名行号
field_name_row = 4
# 导出目标路径
destination = "./samples/json/"
# 文件前缀
file_prefix = "cfg_"

# Erlang导出配置
[schema.erlang]
# 字段名行号
field_name_row = 5
# 导出目标路径
destination = "./samples/erlang/"
# 文件前缀
file_prefix = "cfg_"
# record前缀
record_prefix = "cfg_"

# typescript导出配置
[schema.typescript]
# 字段名行号
field_name_row = 4
# 导出目标路径
destination = "./samples/typescript/"