# cfg-exporter 配置模板

# 配置文件路径
source = "./samples/configs"
# 字段描述行号
field_comment_row = 1
# 字段类型行号
field_type_row = 2
# 字段装饰器行号
field_decorator_row = 3
# 主体数据起始行号
body_start_row = 6
# 是否启用ui界面
ui = false
# 是否检验生成后的配置
verify = true
# 默认执行的导出模式
default_schema =""

# Erlang导出配置
[schema.erlang]
# 字段名行号
field_name_row = 5
# 导出目标路径
destination = "./samples/erlang/"
# 文件前缀
file_prefix = "cfg_"
# 表名前缀
table_name_prefix = "cfg_"

# typescript导出配置
[schema.typescript]
# 字段名行号
field_name_row = 4
# 导出目标路径
destination = "./samples/typescript/"
# 文件前缀
file_prefix = ""
# 表名前缀
table_name_prefix = "fbs_"

# json导出配置
[schema.json]
# 字段名行号
field_name_row = 4
# 导出目标路径
destination = "./samples/json/"
# 文件前缀
file_prefix = ""
# 表名前缀
table_name_prefix = "fbs_"

# flatbuffers导出配置
[schema.flatbuffers]
# 字段名行号
field_name_row = 4
# 导出目标路径
destination = "./samples/flatbuffers/"
# 文件前缀
file_prefix = ""
# 表名前缀
table_name_prefix = "fbs_"
# flatc可执行文件的位置
flatc = "./samples/flatbuffers/flatc.exe"
# 命名空间
namespace = ""